### ISSUE TITLE
Cant pour paltinum blocks or ingots

### ISSUE THREAD

**Issue by Mogibear** [Mrthomas20121-Mods/Tinkers-Reforged#10]
I think there is a similar bug to https://github.com/Mrthomas20121/Tinkers-Reforged/issues/8 where i can pour plat to different casts, but not to ingots or blocks.

**Comment by Mrthomas20121** [comment]
im aware of this. it's fixed in dev. i had a few exams lately didn't have time to work on it and push it to curseforge
