### ISSUE TITLE
Mekanism Recipe Issue

### ISSUE THREAD

**Issue by Cazadorsniper** [Mrthomas20121-Mods/Tinkers-Reforged#11]
This is the same as #7 only with Mekanism metals like osmium, refined obsidian and refined glowstone ingots.

**Comment by Mrthomas20121** [comment]
i know what's wrong. i fixed it in dev.

**Comment by Cazadorsniper** [comment]
Ok.

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/2960840 hopefully this build fix it!
