### ISSUE TITLE
Server Crash After Update

### ISSUE THREAD

**Issue by mxnmnm** [Mrthomas20121-Mods/Tinkers-Reforged#16]
https://gist.github.com/mxnmnm/15bb9966088ef1ee21582a484bd2a429

Updated the mod on a server from 1.3.2 to 1.3.3 and then the server crashed.

**Comment by Mrthomas20121** [comment]
fixed. https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/3017000
