### ISSUE TITLE
Metallurgy 4 Support please.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Mrthomas20121-Mods/Tinkers-Reforged#20]
There is no up to date mod that supports Metallurgy 4. Please send help.

**Comment by P3rf3ctXZer0** [comment]
https://www.curseforge.com/minecraft/mc-mods/metallurgy-4-reforged

**Comment by P3rf3ctXZer0** [comment]
https://www.curseforge.com/minecraft/customization/metallurgytweaks

**Comment by Mrthomas20121** [comment]
ah yes asking for tinkers support when the mod already have built in support for it
