### ISSUE TITLE
Some Configs Don't seem to work

### ISSUE THREAD

**Issue by Collecter128** [Mrthomas20121-Mods/Tinkers-Reforged#22]
I may have made a mistake but setting some materials to be disabled didn't seem to work. 

What I have typed into the Config files:

    S:materials <
	aluminum
	iridium
	platinum
	titanium
	osmium
	thaumium
     >

Maybe I typed it wrong, or maybe it isn't working?

**Comment by Mrthomas20121** [comment]
material names start with `ref_`.
