### ISSUE TITLE
Fluids broken, doubly so with PlusTiC, Tinkers' Evolution

### ISSUE THREAD

**Issue by cha0sbuster** [Mrthomas20121-Mods/Tinkers-Reforged#25]
So while troubleshooting this issue over at Tinkers Evolution: phantamanta44/tinkers-evolution#58

I narrowed the issue down to this mod and revealed a few more. Get ready for a dump, half the week went into this.

1. Fluids appear to be broken in the current version of Tinkers' Reforged.
![image](https://user-images.githubusercontent.com/22553697/97762827-28891100-1ae0-11eb-8104-702ed5be84c2.png)

While they are visible in buckets, they're neither visible in the smeltery or in the world.

2. Only the Gladius and Lightsword are visible in JEI, nothing else is visible or craftable.
The rest aren't even listed in Materials and You, their pages replaced with errors:
![image](https://user-images.githubusercontent.com/22553697/97762934-69812580-1ae0-11eb-9cb9-addba5d3cc37.png)

3. Neither PlusTiC nor Tinkers' Evolution work properly with Reforged installed. PlusTiC's names (at least for fluids) for refined obsidian and glowstone are different from Reforged (Reforged separates with an underscore, PlusTiC does not, they're just "refinedobsidian" and "refinedglowstone") causing them to be registered as separate materials, breaking packs that use PlusTiC's fluids such as Enigmatica 2. Tinkers' Evolution's override function, while it does fix duplicate tools, does not fix fluids (as visible in the linked issue).

Aluminum's name is broken, but its texture works (as it's provided by vanilla TiC).

**Comment by Mrthomas20121** [comment]
i'm aware of all of these problems.

**Comment by cha0sbuster** [comment]
Cool; hope details help with getting them fixed ^^

Let me know if you need anything else from me. Test instance is ready to go still.

**Comment by Mrthomas20121** [comment]
fluids should be fixed now. i rewrote some part of the mod, that's why it took this long to fix(also having uni exams didn't help). i'm working on a better config rn because the current config doesn't please me. Tinkers' Evolution should work with tinkers reforged now.

**Comment by cha0sbuster** [comment]
Awesome!! I'll give it a go and see if it works now.

**Comment by cha0sbuster** [comment]
OH, it's not out quite yet. Not sure how to build a mod from source but if I figure it out before the update's pushed, I'll let you know :P

**Comment by Mrthomas20121** [comment]
yeah it's not out yet, it should be out today. i'm only missing lang stuff
