### ISSUE TITLE
[Request] Heat and Climate mod Support

### ISSUE THREAD

**Issue by Gonbuto** [Mrthomas20121-Mods/Tinkers-Reforged#29]
Could you add support for Heat and Climate mod ,if you would not mind?
https://www.curseforge.com/minecraft/mc-mods/heat-and-climate

**Comment by Mrthomas20121** [comment]
i can look into it

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/3178347 there you go.
