### ISSUE TITLE
Tinkers Book Errors

### ISSUE THREAD

**Issue by BaxAndrei** [Mrthomas20121-Mods/Tinkers-Reforged#30]
![image](https://user-images.githubusercontent.com/12484505/106014905-9c7a8b80-60c6-11eb-9ff1-fdde6c032096.png)

**Comment by BaxAndrei** [comment]
Also there are few pages missing for modifiers
![image](https://user-images.githubusercontent.com/12484505/106017396-1744a600-60c9-11eb-8ab2-78e7869b83fe.png)
![image](https://user-images.githubusercontent.com/12484505/106017428-1d3a8700-60c9-11eb-8693-1ab71f733844.png)

I also checked config and disabled all modules for mods that I don`t have installed

**Comment by Mrthomas20121** [comment]
already known. it will be fixed.

**Comment by BaxAndrei** [comment]
Thank you. I searched first your git, but there was no issue about that so I created one. Can you please let me know when will be patched?

**Comment by Mrthomas20121** [comment]
sure

**Comment by Mrthomas20121** [comment]
it's fixed now, should be on curseforge soon

**Comment by BaxAndrei** [comment]
Ty.
