### ISSUE TITLE
Aether II 

### ISSUE THREAD

**Issue by Overshakes** [Mrthomas20121-Mods/Tinkers-Reforged#36]
Hey, I love tinker and aether II, I know aether is supported by another addon but I prefere Ather II Highlands Update

https://www.curseforge.com/minecraft/mc-mods/the-aether-ii

Can you add this mod in your addon pls

thank you for reading

**Comment by Mrthomas20121** [comment]
i'm not planning on support aether 2 in 1.12. i might support it in 1.16

**Comment by Overshakes** [comment]
I'm waiting aether II for 1.16.5, your reply is good news

thanks :)

**Comment by Mrthomas20121** [comment]
Well i have news, as of 1.16 i won't support mods anymore, instead i'll add my own materials.
if you wish to have x mod supported ask the guys over Materialis for mod compat. his mod is the reason i stopped doing compat for mods. we don't need 2 or 3 mods doing Tinkers mod compat, we only need 1.
