### ISSUE TITLE
Divine RPG Support

### ISSUE THREAD

**Issue by Revolutiion** [Mrthomas20121-Mods/Tinkers-Reforged#37]
Hello! I was just wondering if it would be possible to add support for the mod DivineRPG and its ores. (Realmite, Arlemite, Rupee, etc.)

https://www.curseforge.com/minecraft/mc-mods/official-divinerpg

Thanks

**Comment by Mrthomas20121** [comment]
sorry but i'm not adding new mod support in the 1.12 version of the mod.
