### ISSUE TITLE
Qivium material very imbalance

### ISSUE THREAD

**Issue by olegikoligik** [Mrthomas20121-Mods/Tinkers-Reforged#40]
Maybe it only my bug, but qivium material looks like a cheat. They have very hight damage (exemple: sword have 56.88 damage). Does he have a debuff? Because i dont have any debuf. But I see in description "half hp", maybe this is debaf? But I don't get the debuff when I use the Qivium item.

**Version mc: 1.12**

**Comment by Mrthomas20121** [comment]
the material make you lose 10 hearts while holding it. by lose i mean you literally can't use these hearts, they're gone, you get them back while not holding it. unless a mod is messing with it you should lose these hearts. i tested the material myself

**Comment by olegikoligik** [comment]
Strange, maybe some mods change something. I have only 10 hearts (I have no mods that increase this value). And in theory I should die with this item (qivium)
