### ISSUE TITLE
Some random bugs (small and large)

### ISSUE THREAD

**Issue by Gebcrafter** [Mrthomas20121-Mods/Tinkers-Reforged#41]
Hey, I love this mod. I was definitely needing a better alternative to PlusTiC. I'm on 1.5.6.

1) The alloys' blocks dont have localized names, textures, and can't be turned into ingots [fig. A](https://i.imgur.com/s1LC3pf.png)
2) Various traits don't have localized names and their formatting is very strange [fig. B](https://i.imgur.com/i0KrHua.png) [fig. C](https://i.imgur.com/h0LPZGX.png) [fig. D](https://i.imgur.com/GbEexMf.png) 
3) Kovar is unobtainable and kovar glass is useless? I think this is just a WIP aspect of the mod so likely not a "bug"

**Comment by Mrthomas20121** [comment]
1. i'm aware of this but no fix yet(i might push one last build to curseforge)
2. i was not aware of this but i'll see what i can do.
3. Kovar is not unobtainable, see Kovar fluid. Kovar glass is a blast resistant glass btw.

**Comment by Gebcrafter** [comment]
Ah I see, thanks.

I also noticed something else: sapphire fluid and materials are [gray](https://i.imgur.com/xyhlzmQ.png). Is this intended? I'd imagine they should be blue

**Comment by Mrthomas20121** [comment]
this is a bug afaik.
