### ISSUE TITLE
Qivium and Lavium

### ISSUE THREAD

**Issue by Swestie** [Mrthomas20121-Mods/Tinkers-Reforged#43]
Not too sure how to obtain or make Lavium and qivium, Cant find anything about it

**Comment by Mrthomas20121** [comment]
See JEI for recipes.

**Comment by Swestie** [comment]
There are no recipes on how tomake it, just that it exists

**Comment by JewelLiane** [comment]
Yeah I figured it out. You need a cobalt repair kid and pour liquid soul on the cobalt for lavium, and magma for qivium, and you need a bloodshroom sharperner  and pout obsidian on it for wavy.  You can also do this with an ingot or a cobalt block. Just smelt magma blocks and soul sand to get teh stuff you need to make them.
