### ISSUE TITLE
Lavium ore duping

### ISSUE THREAD

**Issue by DonkeyJuice101** [Mrthomas20121-Mods/Tinkers-Reforged#44]
is the miners blessing from lavium supposed to duplicate ores (even ones I place manually in survival), if so is it just and infinite source of ores?

**Comment by Mrthomas20121** [comment]
not intentional.

**Comment by Mrthomas20121** [comment]
i might just change the trait entirely

**Comment by Mrthomas20121** [comment]
i reworked miners blessing, now it has have a chance of giving 1 coal(2%+modifier level) or charcoal(1%+modifier level) when breaking blocks below 20.

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/3732104 just uploaded the change
