### ISSUE TITLE
[1.18.2][Suggestion] Material checkbox

### ISSUE THREAD

**Issue by ffuentesm** [Mrthomas20121-Mods/Tinkers-Reforged#45]
Would be nice if added an individual materia compatibility checkbox in the settings?
So we can turn off a specific material compatibility. I mostly asking that since some mods add the same material compatibility with different stats and this way you could be able to choose which to pick.
Like how Tinker's Reforged and Materialis both add aluminum.

I also had the same problem back in 1.16.5 where different mods coffered the same popular material, such as Manasteel or Livingwood.

**Comment by Mrthomas20121** [comment]
i'm not adding materials compat anymore. also aluminum is just a crafting material it doesn't have a tinkers material so i don't know what you're talking about. all of my mod tinkers materials are unique.
