### ISSUE TITLE
Bauxite and Kepu Ore

### ISSUE THREAD

**Issue by AFKafe** [Mrthomas20121-Mods/Tinkers-Reforged#46]
Greetings,

On version 1.18.2-1.0.4, Bauxite Ore, Deepslate Bauxite Ore and Kepu Ore have no associated tools and therefore are not mined faster with a pickaxe than by hand.

Would it be possible to add the "pickaxe" tool to them?

Thank you for your mod

**Comment by Mrthomas20121** [comment]
will be fixed in the next release
