### ISSUE TITLE
JEI auto install when this mod Install (CURSEFORGE)

### ISSUE THREAD

**Issue by VirtualGaming1** [Mrthomas20121-Mods/Tinkers-Reforged#47]
Just want to let you know that I use REI because I was having issue with JEI when connecting with a server (not sure this presist) but found out that after installing this that JEI install as well. You should change JEI as Optional as it should not be as a Hard Reqirement.
The thing is now that I cannot have this mod in my modpack because there will be chances of JEI be install to other users of the modpack and will make the game crash from the start.

Linking this with same issue that the author of the other mod changed it to Optional for his future updates.
Can I get an update or changes on curseforge side that it will not install JEI as this mod get install.
Thanks

https://github.com/Sirttas/ElementalCraft/issues/80

**Comment by Mrthomas20121** [comment]
i can do that.

**Comment by Mrthomas20121** [comment]
newest release should no longer require jei

**Comment by VirtualGaming1** [comment]
Thanks!
