### ISSUE TITLE
[1.18.2] Felsteel and Chorus Metal Possible Overlap?

### ISSUE THREAD

**Issue by NyvexOfShadows** [Mrthomas20121-Mods/Tinkers-Reforged#48]
Hello!

Just started playing with the mod, noticing now that the Encyclopedia's description of Felsteel and Chorus Metal are the exact same:

"Deal more damage to things in the nether but deal less damage to things in the end"

Is this intended, or is one of these two supposed to work the _opposite_ way? I would assume Felsteel would have increased nether damage and decreased end damage.

**Comment by Mrthomas20121** [comment]
known issue
