### ISSUE TITLE
Conflict with ConstructsArmory

### ISSUE THREAD

**Issue by Cereza69** [Mrthomas20121-Mods/Tinkers-Reforged#5]
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Reforged (tinkers_reforged)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Trait to "reforged_fluix_crystal": Trait "skeletal_armor" was already registered by Unknown`

**Comment by Cereza69** [comment]
Try the tinkers_reforged-1.1.3
after testing, conflict the conarm-1.12.2-1.2.5.8
since Construct's Armory loaded first, Tinkers' Reforged should check for conflict
hope you can fix it, thanks

**Comment by Mrthomas20121** [comment]
update to the latest version. i fixed that in future version.
