### ISSUE TITLE
[1.18.2] [1.0.7] Cannot cast pickaxe heads with aluminium cast

### ISSUE THREAD

**Issue by LukeD7** [Mrthomas20121-Mods/Tinkers-Reforged#52]
Firstly, only recently found your mod whilst adding a bunch to my own private modpack. Absolutely love it. However I'm not sure if the following is by design or a bug.

Issue is very simple, I can cast the aluminium pick head cast, but I cannot cast pick heads with it. The cast does nothing. I can cast axe heads, tool rods, bindings all fine. But just not the pick head.

When checking JEI there is no corresponding entries either for casting. But select an axe head cast or tool rod cast and I can see the entries for recipes and usage.

**Comment by Mrthomas20121** [comment]
Tinkers renamed pickaxe cast to pick cast in 1.18. that's why it's not working. i just fixed it and i'm uploading the jar to curse as we speak. thank for reporting it, i would have found it.

**Comment by Mrthomas20121** [comment]
![image](https://user-images.githubusercontent.com/34064092/174618830-65d83777-7d8a-4cb6-b35c-76fa22cc07b4.png)
