### ISSUE TITLE
[1.18.2] Yokel ingot uses Durasteel?

### ISSUE THREAD

**Issue by cata023** [Mrthomas20121-Mods/Tinkers-Reforged#53]
I suspect that this is just something that was missed during development, but it appears that the recipe for a yokel ingot uses molten durasteel instead of yokel.
![image](https://user-images.githubusercontent.com/19790426/178408073-ed67ed0e-eec5-47e0-883a-5f2d9f83fabb.png)

**Comment by cata023** [comment]
Upon further inspection, it appears that wavy ingots and yokel nuggets suffer the same fate.

**Comment by Mrthomas20121** [comment]
this will be fixed in the next update
