### ISSUE TITLE
Config is True for All Tools, but Only Gladius and Lightsword is Available (1.12.2).

### ISSUE THREAD

**Issue by TrevorA02** [Mrthomas20121-Mods/Tinkers-Reforged#58]
Didn't touch the config at all yet 70% of the items are not appearing in JEI or the regular creative menu. All of the new tools are set to true in the config. Is there a fix or something I'm missing to turn on the rest of the tools.

**Comment by Mrthomas20121** [comment]
some tools require a specific mod to be loaded(atum and more)
