### ISSUE TITLE
Scorched and seared ingot tanks perform the same despite description text

### ISSUE THREAD

**Issue by NuancNewt** [Mrthomas20121-Mods/Tinkers-Reforged#59]
Seared ingot tanks claim to hold 48 ingots while scorched tanks claim to hold 3 molten blocks
unless there is some very weird math that im just unware of they should hold different amounts but according to in game both cap out at 4.32 buckets

![1234576910](https://user-images.githubusercontent.com/113639718/190502548-16efb5fe-5bf9-4dcf-b39e-28b69a867b55.png)

**Comment by Mrthomas20121** [comment]
that's a tinkers construct thing, not part of my addon

**Comment by NuancNewt** [comment]
Ahhh shit this is the wrong github i am sorry my dude, found this on a reddit thread and clearly pressed the wrong link. All good delete this as you wish

**Comment by Mrthomas20121** [comment]
https://github.com/SlimeKnights/TinkersConstruct
