### ISSUE TITLE
Aluminum Casts cannot be placed into Cast Chest

### ISSUE THREAD

**Issue by FrijDom** [Mrthomas20121-Mods/Tinkers-Reforged#61]
This mod has been decent so far (though automatically making whitestone tools when trying to make aluminum casts of stone tools is annoying), but I noticed that because they're not being added to the 'casts' tag, aluminum casts can't be placed into the Cast Chest. They work fine otherwise because they're in the multi-use-casts tag.

**Comment by Mrthomas20121** [comment]
the whitestone stuff is from Tinkers. i don't think there is anything i can do about it. as for the casts, it's an oversight on my end and will be fixed

**Comment by FrijDom** [comment]
I figured as much. That's fine, though, since I can always use wooden parts to make them. Thanks!
