### ISSUE TITLE
Bismuth it’s a metal that exists

### ISSUE THREAD

**Issue by SpeedyZ500** [Mrthomas20121-Mods/Tinkers-Reforged#62]
As far as I’m aware there aren’t any Minecraft mods that add Bismuth in 1.18, at least that don’t completely change how Minecraft works, also bismuth crystals look cool, the traits could be like cure, basically you use your tool and it acts like a milk bucket, because bismuth is found in medicine, this is probably a dumb suggestion, but it is similar to lead, but safe for human consumption

**Comment by Mrthomas20121** [comment]
Tinkers Construct has plans to add bismuth to 1.18

**Comment by SpeedyZ500** [comment]
Oh ok, I had thought that was 1.19+ content and not necessarily bismuth, just a ore or material that looks similar, but then I checked again and saw the names were dev names so yeah the one that looks like bismuth is probably going to be bismuth
