### ISSUE TITLE
1.12.2 Crash - Incompatibility with Tesseract or one of it's libraries.

### ISSUE THREAD

**Issue by Handeril** [Mrthomas20121-Mods/Tinkers-Reforged#68]
I'm bumping this from Tesseract's Issue Tracker - as the author is claiming it's an issue with this mod and not theirs.

[The original bug report](https://github.com/SuperMartijn642/Tesseract/issues/69)

Sorry if I seem a bit rude about it. Thank you for your time nonetheless.

**Comment by Mrthomas20121** [comment]
sorry but 1.12.2 is not maintained. all i can you is to not use that specific modifier inside a block breaker.
