### ISSUE TITLE
Some Smeltery recipes don't Work

### ISSUE THREAD

**Issue by Cazadorsniper** [Mrthomas20121-Mods/Tinkers-Reforged#7]
I have gotten reports of some smeltery recipes (melting and casting) don't work with Thermal Foundation metals.

https://github.com/Cazadorsniper/PO3/issues/1088

**Comment by Mrthomas20121** [comment]
will look into it but i think i already fixed that in dev

**Comment by Mrthomas20121** [comment]
![image](https://user-images.githubusercontent.com/34064092/81696539-52804580-9464-11ea-9aff-e92e6d71e3ba.png)
it work just fine for me 🤔 granted some stuff can't be melt but i think it's because the temperature of enderium is too hot.(won't work with lava, need something hotter)

**Comment by Mrthomas20121** [comment]
i could add blazing pyrotheum as a smeltery fluid like plustic did.

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/2954909 hopefully this build fix it
