### ISSUE TITLE
(Suggestion) Make a mod wiki

### ISSUE THREAD

**Issue by TheEffortFighter** [Mrthomas20121-Mods/Tinkers-Reforged#70]
A wiki listing all the materials added by the mod, what they do, and the tags for each material (for modpack makers).

**Comment by Mrthomas20121** [comment]
the tags are simple. if the material is a gem, `forge:gems/gem_name`, if the material is a metal `forge:ingots/material_name`
(replace ingots/gems with dusts and stuf for the other stuff)

also the materials can be found in my mod's book(reforging guide)

i'm working on a balance update so don't expect a wiki just yet

the reforging guide book will include that information when i'm done with the 1.18.2 balance update

**Comment by TheEffortFighter** [comment]
Nice, I was able to find each material and get the tags for them overtime. I was asking about a list though to make it easier to find out every material the mod has to offer without scouring the books (it took me a while with jei to figure out what belonged to base tinkers, reforged, and materialis). I'm making a mod pack with pmmo and the more recent versions require that you manually put in each material and what levels they require, so a list that I could copy and paste the tags and materials from would've been beneficial.
