### ISSUE TITLE
[1.18.2] Missing aluminum casts?

### ISSUE THREAD

**Issue by Overgrowth23** [Mrthomas20121-Mods/Tinkers-Reforged#71]
Version Info:
-Tinkers Reforged 2.0.8
-Minecraft 1.18.2
-Forge 40.2.1
-Tinkers Construct 3.6.4.113

Hi, just wondering if it's a bug on my end that there are no ways of making aluminum casts for Round Plate, Bow Limb, and Bow Grip? They're listed in JEI (Bow grip isn't even listed), but when clicked, no recipe pops up, and nothing happens when I try with the actual smelter. 

As well, I believe the description for Greatsword is broken, and doesn't display in either the tinker's station or the tinkers anvil

![Screenshot 2023-10-19 154300](https://github.com/Mrthomas20121-Mods/Tinkers-Reforged/assets/148503549/5c32bd01-9e2c-4091-a4b4-56de04c86e8a)
![Screenshot 2023-10-19 154502](https://github.com/Mrthomas20121-Mods/Tinkers-Reforged/assets/148503549/007d3f28-8841-41df-bdf5-8b20117c213d)

**Comment by Mrthomas20121** [comment]
that's weird, are you running any other mods?

**Comment by Overgrowth23** [comment]
Yep, I'm using many other mods, but I tried running just tinkers reforged, TiCon, and JEI, and the issue was still there. I could list all the mods down if you need, but it's a long list.
