### ISSUE TITLE
Know Issues for 1.19.2

### ISSUE THREAD

**Issue by Mrthomas20121** [Mrthomas20121-Mods/Tinkers-Reforged#72]
- No issues on the latest version of the mod.

**Comment by wendall911** [comment]
Datagen didn't get run before the latest release.  A few ores are missing from https://github.com/Mrthomas20121-Mods/Tinkers-Reforged/blob/1.19.2/src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json This causes an issue when trying to enforce correct tool.

**Comment by Mrthomas20121** [comment]
it's not a datagen issue. I just forgot to add the non deepslate gem ores to the tag.

**Comment by wendall911** [comment]
Oh, my bad. I somehow thought I saw it was tagged in code. I just made a quick check though. I had a user report the issue with one of my mods, so wanted to make you aware. Thanks!

**Comment by Nxssie** [comment]
Hello,

This method declaration cannot resolve class function getStats or getArtmorStats

```java
@Override
    protected void addMaterialStats() {
        for(EnumMaterial material: EnumMaterial.values()) {
            addMaterialStats(material.id, material.stats.getStats());
            addArmorShieldStats(material.id, material.stats.getArmorStats().getStats(), material.stats.getArmorStats().getStatlessMaterialStats());
        }
    }
```

Seems unused but I'm not familiar with your code and I don't know the responsibilities of each element so glad to understand as necessary to help you

As I'm trying to upgrade forge dependecy to 43.3.8 to improve compatibility with my arclight server I'm also happy to tell you that seems stable

**Comment by Codefreak64** [comment]
Mod won't load due to "java.lang.reflect.InvocationTargetException"

**Comment by Mrthomas20121** [comment]
Its a known issue

**Comment by Mrthomas20121** [comment]
> Hello,
> 
> This method declaration cannot resolve class function getStats or getArtmorStats
> 
> ```java
> @Override
>     protected void addMaterialStats() {
>         for(EnumMaterial material: EnumMaterial.values()) {
>             addMaterialStats(material.id, material.stats.getStats());
>             addArmorShieldStats(material.id, material.stats.getArmorStats().getStats(), material.stats.getArmorStats().getStatlessMaterialStats());
>         }
>     }
> ```
> 
> Seems unused but I'm not familiar with your code and I don't know the responsibilities of each element so glad to understand as necessary to help you
> 
> As I'm trying to upgrade forge dependecy to 43.3.8 to improve compatibility with my arclight server I'm also happy to tell you that seems stable

Why are you doing that?

also why are you not using a forge server? forge(and fabric for that matter) already have plugins it's called server side mods.
also also you're working with a wip version(i'm currently adding support to armor so things are not finished)

**Comment by Nxssie** [comment]
> > Hello,
> > This method declaration cannot resolve class function getStats or getArtmorStats
> > ```java
> > @Override
> >     protected void addMaterialStats() {
> >         for(EnumMaterial material: EnumMaterial.values()) {
> >             addMaterialStats(material.id, material.stats.getStats());
> >             addArmorShieldStats(material.id, material.stats.getArmorStats().getStats(), material.stats.getArmorStats().getStatlessMaterialStats());
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems unused but I'm not familiar with your code and I don't know the responsibilities of each element so glad to understand as necessary to help you
> > As I'm trying to upgrade forge dependecy to 43.3.8 to improve compatibility with my arclight server I'm also happy to tell you that seems stable
> 
> Why are you doing that?
> 
> also why are you not using a forge server? forge(and fabric for that matter) already have plugins it's called server side mods. also also you're working with a wip version(i'm currently adding support to armor so things are not finished)

I actually like spigot plugins functionalities and they work well for me so the most stable server @ 1.19.2 is arclight  and that's why I'm using it

about armor support, I've supposed just after posting the issue so don't worry. Thanks in advance for your work & effort

**Comment by Mrthomas20121** [comment]
it doesn't matter if the plugins works well for you. they were made for vanilla and should be kept that way. 
I will not support a tool that allow plugins to work on forge. USE Forge mods on the server for that purpose. 
If it works, it works but I will not do anything to make it work better.

**Comment by Mrthomas20121** [comment]
If you want to talk with me, you are free to join my discord which is linked on the mod's curseforge/modrinth page.

**Comment by Nxssie** [comment]
> it doesn't matter if the plugins works well for you. they were made for vanilla and should be kept that way. 
> I will not support a tool that allow plugins to work on forge. USE Forge mods on the server for that purpose. 
> If it works, it works but I will not do anything to make it work better.

oh sorry... I'm not talking about you supporting arclight, I know it's a tough work and I don't pretend that, it was some information I considered that could be useful to just know it's compatible, thanks again!

**Comment by DMSledge** [comment]
Thanks for the update. Looks like the long sword no longer has a broad blade requirement which is great, except it looks like the long blade stencil is not available which makes the cast unavailable. Existing casts seem to have disappeared as well.

**Comment by Mrthomas20121** [comment]
I'll look into it

**Comment by Mrthomas20121** [comment]
> Thanks for the update. Looks like the long sword no longer has a broad blade requirement which is great, except it looks like the long blade stencil is not available which makes the cast unavailable. Existing casts seem to have disappeared as well.

turn out I just forgot to add a recipe for it
