### ISSUE TITLE
Mod failing to load

### ISSUE THREAD

**Issue by NoalSimon** [Mrthomas20121-Mods/Tinkers-Reforged#76]
[crash-2024-06-04_21.16.58-fml.txt](https://github.com/user-attachments/files/15571943/crash-2024-06-04_21.16.58-fml.txt)
I have the correct dependencies installed, but it's failing to load

**Comment by NoalSimon** [comment]
Nvm, read another closed issue that it's just not compatible rn

**Comment by Mrthomas20121** [comment]
yeah tinkers updated and it broke my mod, i'm working on that right now, should have a fix by the end of the week
