### ISSUE TITLE
Ticking Entity crash after updating to latest version 1.19.2

### ISSUE THREAD

**Issue by baronpalmer** [Mrthomas20121-Mods/Tinkers-Reforged#77]
[crash-2024-06-11_10.01.32-server.txt](https://github.com/user-attachments/files/15792561/crash-2024-06-11_10.01.32-server.txt)

**Comment by Mrthomas20121** [comment]
Can you try this on a new world

**Comment by Mrthomas20121** [comment]
fixed the issue
