### ISSUE TITLE
Some ally metals like Invar wont pour from smeltery. 

### ISSUE THREAD

**Issue by Mogibear** [Mrthomas20121-Mods/Tinkers-Reforged#8]
I have updated to 1.2.0 on both my server and locally. I have molten invar in my smeltery, but it still will not pour.

**Comment by Mogibear** [comment]
Tried breaking controller and re-smelting more but still wont pour.

**Comment by patchoulisystems** [comment]
I have noticed the molten metals that are labeled as "Thermal Foundation" items seem to be missing the recipes to cast for ingots and blocks.
Affected molten metals (that I could find): Platinum, Iridium, Invar, Signalum, Lumium, Enderium.

Oddly enough, Molten Constantan, which is also labeled as Thermal Foundation, DOES have a recipe for ingot and block casting.

Going for 1.1.3 (bundled with project ozone 3) to 1.2.0 DID fix the broken item names however, see my screenshots for reference.

1.1.3
![image](https://user-images.githubusercontent.com/65249613/81732799-ff57c400-945e-11ea-9756-ae020985e526.png)

1.2.0
![image](https://user-images.githubusercontent.com/65249613/81731773-6d9b8700-945d-11ea-9d1b-1beb1ba28417.png)

I am using PO3-3.3.57, just swapped out the mod using MultiMC.
I'm pretty new to this, so this issue might not even be related to Tinkers Reforged, just trying to get some additional info out there.

**Comment by Mogibear** [comment]
@patchoulisystems Are you able to actually able to pour invar? Like if I try to make invar ingots nothing happens.

**Comment by patchoulisystems** [comment]
Poked at it a bit more and some of the invar stuff from "thermal foundation" won't even melt. See screenshot:
![image](https://user-images.githubusercontent.com/65249613/81739012-a1c87500-9468-11ea-84ef-234fab8640c3.png)
Tested platinum and it also does not melt. Seems like the affected metals aren't considered "tinkers-constructable" if that makes sense.

Invar will pour into tool head casts, but not into ingot cast or block cast.

On the bright side blazing pyrotheum works in the smeltery

**Comment by Cazadorsniper** [comment]
For now I have this fixed in dev using crafttweaker.

**Comment by Mrthomas20121** [comment]
oops mb. fixed that in dev,

**Comment by Mrthomas20121** [comment]
https://github.com/Mrthomas20121/Tinkers-Reforged/commit/7cbc7ddae4ee3956ab5b938e15753807e618a8c8
https://github.com/Mrthomas20121/Tinkers-Reforged/commit/b9e12fdfd93530d05e9b56e0cf60226547902646

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/2955569
