### ISSUE TITLE
[Suggestion] Rework gem materials into modifiers

### ISSUE THREAD

**Issue by MarioSMB** [Mrthomas20121-Mods/Tinkers-Reforged#80]
Tinker's Construct in general does not include gems as a tool material, but rather as a tool modifier.  
Diamonds and emeralds for example add bonus stats to an existing tool instead of being something you can make tools out of.  

Applying a similar logic to the gems added by this mod (epidote etc) would be nice to benefit cohesion, thanks!

**Comment by Mrthomas20121** [comment]
I will not do that. I've been doing gem materials since the 1.12 days, i'm not gonna change it just for it to be "coherent" with tinker.

**Comment by PurplikDev** [comment]
heheheha

**Comment by MarioSMB** [comment]
That's a shame - I think it would be cool to be able to apply epidote's critical damage boost to existing tools rather than as a weird handle made of cast gems, as a sidegrade to emeralds and diamonds (along with the other mod gems of course).  

For what it's worth having it be that way since 1.12 makes less sense; Tinker's Construct has fundamentally changed a great deal since those versions, what may have fit well back then is very much out of place now.

**Comment by Mrthomas20121** [comment]
i'll have you remember tinker already had diamond and emerald as modifier in 1.12, I didn't do it in 1.12, I won't do it now. 

you're free to change that with a datapack.

**Comment by MarioSMB** [comment]
Fair enough, I figured 1.12 is a long enough time span where some designs might be up for debate, but it is your mod and your decision to keep it as it is, so I won’t argue there.  
Thank you for your consideration.
